In [8]:
!pip install kaggle

In [9]:
from google.colab import files
files.upload()

Saving kaggle.json to kaggle (1).json


{'kaggle.json': b'{"username":"arshad7","key":"69772f07db322f48394e6cdc148a976a"}'}

In [0]:
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/

In [0]:
!chmod 600 ~/.kaggle/kaggle.json

In [12]:
!kaggle competitions download -c digit-recognizer

 74% 54.0M/73.2M [00:00<00:00, 62.3MB/s]
100% 73.2M/73.2M [00:00<00:00, 137MB/s] 
 84% 41.0M/48.8M [00:00<00:00, 61.0MB/s]
100% 48.8M/48.8M [00:00<00:00, 133MB/s] 
  0% 0.00/235k [00:00<?, ?B/s]
100% 235k/235k [00:00<00:00, 144MB/s]


In [97]:
!ls

kaggle (1).json  sample_data		test.csv
kaggle.json	 sample_submission.csv	train.csv


In [0]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
import seaborn as sns
%matplotlib inline

In [79]:
train = pd.read_csv("train.csv")
test = pd.read_csv("test.csv")
train.head()

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0      1       0       0       0       0       0       0       0       0   
1      0       0       0       0       0       0       0       0       0   
2      1       0       0       0       0       0       0       0       0   
3      4       0       0       0       0       0       0       0       0   
4      0       0       0       0       0       0       0       0       0   

   pixel8    ...     pixel774  pixel775  pixel776  pixel777  pixel778  \
0       0    ...            0         0         0         0         0   
1       0    ...            0         0         0         0         0   
2       0    ...            0         0         0         0         0   
3       0    ...            0         0         0         0         0   
4       0    ...            0         0         0         0         0   

   pixel779  pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0         0  
1         0         0         0         0         0  
2         0         0         0         0         0  
3         0         0         0         0         0  
4         0         0         0         0         0  

[5 rows x 785 columns]

In [78]:
name = train.columns.drop('label')


Index(['pixel0', 'pixel1', 'pixel2', 'pixel3', 'pixel4', 'pixel5', 'pixel6',
       'pixel7', 'pixel8', 'pixel9',
       ...
       'pixel774', 'pixel775', 'pixel776', 'pixel777', 'pixel778', 'pixel779',
       'pixel780', 'pixel781', 'pixel782', 'pixel783'],
      dtype='object', length=784)

In [0]:
x=train.drop(columns='label')
x = x.iloc[:5000,:]

y=train['label']
y=y.iloc[:5000]


In [0]:
x=x/255


In [137]:
x.head()

pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
1     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
2     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
3     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
4     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   

   pixel9    ...     pixel774  pixel775  pixel776  pixel777  pixel778  \
0     0.0    ...          0.0       0.0       0.0       0.0       0.0   
1     0.0    ...          0.0       0.0       0.0       0.0       0.0   
2     0.0    ...          0.0       0.0       0.0       0.0       0.0   
3     0.0    ...          0.0       0.0       0.0       0.0       0.0   
4     0.0    ...          0.0       0.0       0.0       0.0       0.0   

   pixel779  pixel780  pixel781  pixel782  pixel783  
0       0.0       0.0       0.0       0.0       0.0  
1       0.0       0.0       0.0       0.0       0.0  
2       0.0       0.0       0.0       0.0       0.0  
3       0.0       0.0       0.0       0.0       0.0  
4       0.0       0.0       0.0       0.0       0.0  

[5 rows x 784 columns]

In [0]:
from sklearn.cross_validation import train_test_split
X_train, X_test, y_train, y_test = train_test_split( x, y, test_size=0.3, random_state=101)

In [0]:
from sklearn.svm import SVC
svc = SVC()

In [149]:
svc.fit(X_train,y_train)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [0]:
pred = svc.predict(X_test)

In [0]:
from sklearn.metrics import classification_report, confusion_matrix

In [152]:
print(confusion_matrix(y_test,pred))
print('\n')
print(classification_report(y_test,pred))

[[137   0   1   1   0   2   0   1   1   0]
 [  0 148   0   2   0   0   0   0   2   0]
 [  0   1 140   0   5   0   3   2   5   1]
 [  1   2   5 138   0   5   0   0   4   1]
 [  0   0   0   0 126   1   2   0   0  14]
 [  0   7   1   3   2 123   1   0   1   1]
 [  1   1   3   1   1   2 159   0   0   0]
 [  0   6   2   0   1   0   1 144   0   7]
 [  2   4   0   4   0  10   1   1 125   2]
 [  1   1   1   1   3   1   0   5   1 118]]


             precision    recall  f1-score   support

          0       0.96      0.96      0.96       143
          1       0.87      0.97      0.92       152
          2       0.92      0.89      0.90       157
          3       0.92      0.88      0.90       156
          4       0.91      0.88      0.90       143
          5       0.85      0.88      0.87       139
          6       0.95      0.95      0.95       168
          7       0.94      0.89      0.92       161
          8       0.90      0.84      0.87       149
          9       0.82      0.89    