[View in Colaboratory](https://colab.research.google.com/github/arshadshk/Digit-Classifier-Kaggle-SVM/blob/master/svm_final_subitted.ipynb)

In [2]:
!pip install kaggle

    100% |████████████████████████████████| 61kB 4.0MB/s 
    100% |████████████████████████████████| 235kB 7.8MB/s 
  Running setup.py bdist_wheel for kaggle ... - \ done
  Stored in directory: /root/.cache/pip/wheels/44/2c/df/22a6eeb780c36c28190faef6252b739fdc47145fd87a6642d4
  Running setup.py bdist_wheel for python-slugify ... - done
  Stored in directory: /root/.cache/pip/wheels/e3/65/da/2045deea3098ed7471eca0e2460cfbd3fdfe8c1d6fa6fcac92
Successfully built kaggle python-slugify


In [4]:
from google.colab import files
files.upload()

Saving kaggle.json to kaggle.json


{'kaggle.json': b'{"username":"arshad7","key":"69772f07db322f48394e6cdc148a976a"}'}

In [0]:
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/

In [0]:
!chmod 600 ~/.kaggle/kaggle.json

In [5]:
!kaggle competitions download -c digit-recognizer

train.csv: Skipping, found more recently modified local copy (use --force to force download)
test.csv: Skipping, found more recently modified local copy (use --force to force download)
sample_submission.csv: Skipping, found more recently modified local copy (use --force to force download)


In [6]:
!ls

kaggle.json  sample_data  sample_submission.csv  test.csv  train.csv


In [0]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
import seaborn as sns
%matplotlib inline

In [8]:
train = pd.read_csv("train.csv")
test = pd.read_csv("test.csv")
train.head()

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0      1       0       0       0       0       0       0       0       0   
1      0       0       0       0       0       0       0       0       0   
2      1       0       0       0       0       0       0       0       0   
3      4       0       0       0       0       0       0       0       0   
4      0       0       0       0       0       0       0       0       0   

   pixel8    ...     pixel774  pixel775  pixel776  pixel777  pixel778  \
0       0    ...            0         0         0         0         0   
1       0    ...            0         0         0         0         0   
2       0    ...            0         0         0         0         0   
3       0    ...            0         0         0         0         0   
4       0    ...            0         0         0         0         0   

   pixel779  pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0         0  
1         0         0         0         0         0  
2         0         0         0         0         0  
3         0         0         0         0         0  
4         0         0         0         0         0  

[5 rows x 785 columns]

In [0]:
name = train.columns.drop('label')


In [0]:
x=train.drop(columns='label')
x = x.iloc[:5000,:]

y=train['label']
y=y.iloc[:5000]


In [0]:
x=x/255


In [20]:
y.head()

0    1
1    0
2    1
3    4
4    0
Name: label, dtype: int64

In [21]:
from sklearn.cross_validation import train_test_split
X_train, X_test, y_train, y_test = train_test_split( x, y, test_size=0.3, random_state=101)

/usr/local/lib/python3.6/dist-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [0]:
from sklearn.svm import SVC
svc = SVC(C=3,gamma=0.03,verbose=3)

In [23]:
svc.fit(X_train,y_train)


[LibSVM]

SVC(C=3, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=0.03, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=3)

In [0]:
pred = svc.predict(X_test)

In [56]:
pred

array([9, 4, 5, ..., 2, 4, 9])

In [0]:
from sklearn.metrics import classification_report, confusion_matrix

In [26]:
print(confusion_matrix(y_test,pred))
print('\n')
print(classification_report(y_test,pred))

[[141   0   0   0   0   0   0   0   1   1]
 [  0 146   1   2   0   0   0   1   2   0]
 [  0   0 151   0   2   0   1   0   1   2]
 [  0   1   6 145   0   2   0   0   2   0]
 [  0   0   0   0 140   0   1   0   0   2]
 [  0   1   0   0   0 136   2   0   0   0]
 [  1   0   3   0   2   1 160   0   1   0]
 [  0   0   1   0   1   0   0 155   2   2]
 [  1   3   0   4   0   4   0   1 135   1]
 [  1   0   1   0   0   1   0   4   0 125]]


             precision    recall  f1-score   support

          0       0.98      0.99      0.98       143
          1       0.97      0.96      0.96       152
          2       0.93      0.96      0.94       157
          3       0.96      0.93      0.94       156
          4       0.97      0.98      0.97       143
          5       0.94      0.98      0.96       139
          6       0.98      0.95      0.96       168
          7       0.96      0.96      0.96       161
          8       0.94      0.91      0.92       149
          9       0.94      0.95    

In [0]:
from sklearn.model_selection import GridSearchCV

In [0]:
param = {'C':[3,5,7,9,11,20],'gamma':[0.01,0.02,0.03,0.9,0.5]}

In [0]:
grid = GridSearchCV(SVC(),param,verbose=3)

In [37]:
grid.fit(X_train,y_train)

Fitting 3 folds for each of 30 candidates, totalling 90 fits
[CV] C=3, gamma=0.01 .................................................
[CV] ........ C=3, gamma=0.01, score=0.9376068376068376, total=   3.5s
[CV] C=3, gamma=0.01 .................................................


[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    5.8s remaining:    0.0s


[CV] ........ C=3, gamma=0.01, score=0.9356223175965666, total=   3.0s
[CV] C=3, gamma=0.01 .................................................


[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:   11.1s remaining:    0.0s


[CV] ......... C=3, gamma=0.01, score=0.951931330472103, total=   3.0s
[CV] C=3, gamma=0.02 .................................................
[CV] ........ C=3, gamma=0.02, score=0.9487179487179487, total=   4.3s
[CV] C=3, gamma=0.02 .................................................
[CV] ........ C=3, gamma=0.02, score=0.9381974248927039, total=   4.2s
[CV] C=3, gamma=0.02 .................................................
[CV] ........ C=3, gamma=0.02, score=0.9553648068669528, total=   4.2s
[CV] C=3, gamma=0.03 .................................................
[CV] ........ C=3, gamma=0.03, score=0.9478632478632478, total=   5.8s
[CV] C=3, gamma=0.03 .................................................
[CV] ........ C=3, gamma=0.03, score=0.9399141630901288, total=   5.7s
[CV] C=3, gamma=0.03 .................................................
[CV] ........ C=3, gamma=0.03, score=0.9562231759656652, total=   5.7s
[CV] C=3, gamma=0.9 ..................................................
[CV] .

[Parallel(n_jobs=1)]: Done  90 out of  90 | elapsed: 15.3min finished


GridSearchCV(cv=None, error_score='raise',
       estimator=SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False),
       fit_params=None, iid=True, n_jobs=1,
       param_grid={'C': [3, 5, 7, 9, 11, 20], 'gamma': [0.01, 0.02, 0.03, 0.9, 0.5]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=3)

In [1]:
grid.best_params_

NameError: ignored

In [0]:
xfinal =train.drop(columns='label')
xfinal = x.iloc[:,:]

yfinal =train['label']
yfinal =y.iloc[:]

xfinal=xfinal/255







In [31]:
xfinal.head()

pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
1     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
2     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
3     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
4     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   

   pixel9    ...     pixel774  pixel775  pixel776  pixel777  pixel778  \
0     0.0    ...          0.0       0.0       0.0       0.0       0.0   
1     0.0    ...          0.0       0.0       0.0       0.0       0.0   
2     0.0    ...          0.0       0.0       0.0       0.0       0.0   
3     0.0    ...          0.0       0.0       0.0       0.0       0.0   
4     0.0    ...          0.0       0.0       0.0       0.0       0.0   

   pixel779  pixel780  pixel781  pixel782  pixel783  
0       0.0       0.0       0.0       0.0       0.0  
1       0.0       0.0       0.0       0.0       0.0  
2       0.0       0.0       0.0       0.0       0.0  
3       0.0       0.0       0.0       0.0       0.0  
4       0.0       0.0       0.0       0.0       0.0  

[5 rows x 784 columns]

In [0]:
svcfinal = SVC(C=3,gamma=0.03,verbose=3)

In [33]:
svcfinal.fit(xfinal,yfinal)

[LibSVM]

SVC(C=3, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=0.03, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=3)

In [0]:
test = pd.read_csv('test.csv')

In [0]:
test =test/255

In [0]:
s = pd.read_csv('sample_submission.csv')

In [0]:
fpredictions = svcfinal.predict(test)

In [64]:
f

AttributeError: ignored

In [0]:
b=range(1,28001)
submissions = pd.DataFrame({'ImageId':b,'Label':fpredictions})

In [0]:
submissions.to_csv('submissions.csv',index=False)

In [74]:
!ls

kaggle.json  sample_submission.csv  test.csv
sample_data  submissions.csv	    train.csv


# New Section

# New Section